---
all:
  children:
    server:
      hosts:
        #        ubuntu-2404:
        #          container_image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
        ubuntu-2604:
          container_image: docker.io/geerlingguy/docker-ubuntu2604-ansible:latest
