---
# - name: Import prerequisites
#  ansible.builtin.import_tasks: prerequisites.yaml

- name: Install nagios from repository
  ansible.builtin.import_tasks: install.yaml
  when:
    - anro_nagios_install | bool

- name: Configure nagios and apache
  ansible.builtin.import_tasks: configure.yaml
  when:
    - anro_nagios_cfgure | bool


# - name: Build nagios core from source
#  ansible.builtin.import_tasks: build-nagios.yaml
