---
- name: Configure system mail name
  ansible.builtin.copy:
    content: "{{ anro_nagios_server_name }}\n"
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"
  notify: Validate Postfix configuration

- name: Configure Postfix
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: Validate Postfix configuration
