---
- name: Configure system mail name
  ansible.builtin.copy:
    content: "{{ anro_nagios_server_name }}\n"
    dest: /etc/mailname
    owner: root
    group: root
    mode: "0644"
  notify: anro_restart_postfix

- name: Configure Postfix sender canonical map
  ansible.builtin.template:
    src: etc/postfix/sender_canonical.j2
    dest: /etc/postfix/sender_canonical
    owner: root
    group: root
    mode: "0644"
  notify:
    - anro_restart_postfix

- name: Configure Postfix outbound header checks
  ansible.builtin.template:
    src: etc/postfix/smtp_header_checks.j2
    dest: /etc/postfix/smtp_header_checks
    owner: root
    group: root
    mode: "0644"
  notify:
    - anro_restart_postfix

- name: Configure Postfix
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: anro_restart_postfix
