---
- name: Ensure Postfix has requested state
  ansible.builtin.service:
    name: postfix
    enabled: "{{ anro_nagios_postfix_service_enabled }}"
    state: "{{ anro_nagios_postfix_service_state }}"
  when: anro_nagios_postfix_enabled | bool

- name: Ensure Apache has requested state
  ansible.builtin.service:
    name: apache2
    enabled: "{{ anro_nagios_apache_service_enabled }}"
    state: "{{ anro_nagios_apache_service_state }}"
  when: anro_nagios_configure | bool

- name: Ensure Nagios service has requested state
  ansible.builtin.service:
    name: "{{ anro_nagios_service }}"
    enabled: "{{ anro_nagios_service_enabled }}"
    state: "{{ anro_nagios_service_state }}"
