---
- name: Validate Apache configuration
  ansible.builtin.command:
    argv:
      - apachectl
      - configtest
  register: _anro_nagios_apache_configtest
  changed_when: false
  failed_when:
    - _anro_nagios_apache_configtest.rc != 0 or
      'Syntax OK' not in (_anro_nagios_apache_configtest.stderr ~ _anro_nagios_apache_configtest.stdout)
  notify: Reload Apache

- name: Reload Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  throttle: 1
  register: _anro_nagios_apache_reload
  until: _anro_nagios_apache_reload is succeeded
  retries: 5
  delay: 2
  listen:
    - Reload Apache
    - certificate updated
    - cert updated
    - cert update

- name: Validate Nagios configuration
  ansible.builtin.command:
    argv:
      - "{{ anro_nagios_binary }}"
      - -v
      - "{{ anro_nagios_cfg_file }}"
  register: _anro_nagios_configtest
  changed_when: false
  failed_when: >-
    _anro_nagios_configtest.rc != 0 or
    'Total Errors:   0' not in
    (_anro_nagios_configtest.stdout ~ _anro_nagios_configtest.stderr)
  notify: Reload Nagios

- name: Reload Nagios
  ansible.builtin.service:
    name: "{{ anro_nagios_service }}"
    state: reloaded
  when: anro_nagios_service_state != 'stopped'

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
