- name: Validate apache
  ansible.builtin.command: 'apachectl configtest'
  register: _anro_nagios_apache_test
  failed_when:
    - '"Syntax OK" not in _anro_nagios_apache_test.stderr'
    - _anro_nagios_apache_test.rc != 0
  changed_when:
    - '"Syntax OK" in _anro_nagios_apache_test.stderr'
    - _anro_nagios_apache_test.rc == 0
  notify:
    - 'anro_nagios : Reload apache'

- name: Reload apache
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
  listen:
    - certificate updated
    - cert updated
    - cert update
  throttle: 1
  register: _anro_nagios_apache_reload
  until: _anro_nagios_apache_reload is succeeded
  retries: 5
  delay: 2

- name: Validate nagios
  ansible.builtin.command:
    cmd: "{{ anro_nagios_binary }} -v {{ anro_nagios_cfg_file }}"
  changed_when: true
  notify:
    - 'anro_nagios : Reload nagios'
    - 'anro_nagios : Start nagios'

- name: Reload nagios
  ansible.builtin.systemd_service:
    name: "{{ anro_nagios_service }}"
    state: reloaded

- name: Start nagios
  ansible.builtin.systemd_service:
    name: nagios4
    state: started
    enabled: true

- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

# - name: Test anro_nagios nagios
#   ansible.builtin.command: "{{ anro_nagios_binary }} -v {{ anro_nagios_cfg_file }}"
#   listen: Restart anro_nagios services
#   register: _anro_nagios_nagios_test
#   failed_when:
#     - '"Total Errors:   0" not in _anro_nagios_nagios_test.stderr'
#     - _anro_nagios_nagios_test.rc != 0
#   changed_when:
#     - '"Total Errors:   0" in _anro_nagios_nagios_test.stderr'
#     - _anro_nagios_nagios_test.rc == 0
#   notify:
#     - "Reload anro_nagios nagios"
#     - "Service nagios started"
#
# - name: Reload anro_nagios nagios
#  ansible.builtin.systemd_service:
#    name: "{{ anro_nagios_service }}"
#    state: reloaded
#  throttle: 1
#  register: _anro_nagios_nagios_reload
#  until: _anro_nagios_nagios_reload is succeeded
#  retries: 5
#  delay: 2
#  listen: Restart anro_nagios services

