- name: Test anro_nagios apache
  ansible.builtin.command: 'apachectl configtest'
  register: _anro_nagios_apache_test
  failed_when:
    - '"Syntax OK" not in _anro_nagios_apache_test.stderr'
    - _anro_nagios_apache_test.rc != 0
  changed_when:
    - '"Syntax OK" in _anro_nagios_apache_test.stderr'
    - _anro_nagios_apache_test.rc == 0
  notify:
    - "Reload anro_nagios apache"

- name: Reload anro_nagios apache
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
  listen: certificate updated
  throttle: 1
  register: _anro_nagios_apache_reload
  until: _anro_nagios_apache_reload is succeeded
  retries: 5
  delay: 2

- name: Test anro_nagios nagios
  ansible.builtin.command: "{{ anro_nagios_binary }} -v {{ anro_nagios_config_file }}"
  register: _anro_nagios_nagios_test
  failed_when:
    - '"Total Errors:   0" not in _anro_nagios_nagios_test.stderr'
    - _anro_nagios_nagios_test.rc != 0
  changed_when:
    - '"Total Errors:   0" in _anro_nagios_nagios_test.stderr'
    - _anro_nagios_nagios_test.rc == 0
  notify:
    - "Reload anro_nagios nagios"
    - "Service anro_nagios started"

- name: Reload anro_nagios nagios
  ansible.builtin.systemd_service:
    name: "{{ anro_nagios_service }}"
    state: reloaded
  throttle: 1
  register: _anro_nagios_nagios_reload
  until: _anro_nagios_nagios_reload is succeeded
  retries: 5
  delay: 2

- name: Restart anro_nagios postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted
