---
# - name: IMPORT | Verify facts and vars
#  hosts: server
#  tasks:
#    - name: IMPORT | Verify facts and vars
#      ansible.builtin.import_tasks: verify/verify-facts_vars.yml

# - name: IMPORT | Verify system configuration
#  hosts: server
#  tasks:
#    - name: IMPORT | Verify system configuration
#      ansible.builtin.import_tasks: verify/verify-system.yml

# - name: IMPORT | Verify groups and users
#  hosts: server
#  tasks:
#    - name: IMPORT | Verify users
#      ansible.builtin.import_tasks: verify/verify-users.yml

# - name: IMPORT | Verify packages
#  hosts: server
#  tasks:
#    - name: IMPORT | Verify packages
#      ansible.builtin.import_tasks: verify/verify-packages.yml
