---
all:
  children:
    server:
      hosts:
        nagios-minimal-ubuntu-2604:
          container_image: docker.io/geerlingguy/docker-ubuntu2604-ansible:latest
          container_command: /lib/systemd/systemd
          container_privileged: true
          container_volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
